- hosts: practica
  become: True
  tasks: 
        - file: 
               path: /home/asterionmorrigan/holamundo
               state: touch
               owner: root
               group: root
               mode: 0600
