- hosts: practica
  become: True
  tasks:
  - name: update
    action: command apt-get update -y
  - name: install java
    action: command apt install openjdk-11-jdk -y
  - name: java version
    action: command java -version
