apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  #local:
  #  push: false
  googleCloudBuild:
    projectId: biblioteca-dev-316501
  artifacts:
    - image: us.gcr.io/biblioteca-dev-316501/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: us.gcr.io/biblioteca-dev-316501/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: us.gcr.io/biblioteca-dev-316501/book
      context: book
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .